stages:
  - test
  - name: deploy-dev
    if: branch != master
  - name: deploy-prod
    if: branch = master

jobs:
  include:
  - stage: test
    language: node_js
    node_js: 8
    cache:
      yarn: true
      directories:
        - node_modules
        - .cache
    script:
      - yarn test-ci
      - yarn webpack:prod
      - yarn cypress-ci

  - stage: deploy-dev
    language: node_js
    node_js: 8
    cache:
      yarn: true
      directories:
        - node_modules
        - .cache
    script:
      - yarn webpack:prod
    before_deploy:
      - touch public/.nojekyll
    deploy:
      - provider: pages
        skip-cleanup: true
        github-token: ${GITHUB_TOKEN}
        keep-history: true
        repo: knewjade/fumen-for-mobile-dev
        local-dir: public/
        target-branch: master
        on:
          all_branches: true

  - stage: deploy-prod
    language: node_js
    node_js: 8
    cache:
      yarn: true
      directories:
        - node_modules
        - .cache
    script:
      - yarn webpack:prod
    before_deploy:
      - touch public/.nojekyll
    deploy:
      - provider: pages
        skip-cleanup: true
        github-token: ${GITHUB_TOKEN}
        keep-history: true
        repo: knewjade/fumen-for-mobile
        local-dir: public/
        target-branch: master
        on:
          branch: master