language: node_js
node_js:
  - 7
script:
  - yarn webpack
before_deploy:
  - touch public/.nojekyll
deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GITHUB_TOKEN}
  keep-history: true
  repo: knewjade/fumen-for-mobile
  local-dir: public/
  target-branch: master