stages:
  - test
  - name: deploydev
    if: branch != master
  - name: deployprod
    if: branch = master

jobs:
  include:
  - stage: test
    language: node_js
    node_js: 8
    cache:
      yarn: true
      directories:
        - node_modules
    script:
      - yarn test-ci
      - yarn cypress-ci

  - stage: deploydev
    language: node_js
    node_js: 8
    cache:
      yarn: true
      directories:
        - node_modules
    script:
      - yarn webpack:prod
    before_deploy:
      - touch public/.nojekyll
    deploy:
      - provider: pages
        skip-cleanup: true
        github-token: ${GITHUB_TOKEN}
        keep-history: true
        repo: knewjade/fumen-for-mobile-dev
        local-dir: public/
        target-branch: master

  - stage: deployprod
    language: node_js
    node_js: 8
    cache:
      yarn: true
      directories:
        - node_modules
    script:
      - yarn webpack:prod
    before_deploy:
      - touch public/.nojekyll
    deploy:
    - provider: pages
      skip-cleanup: true
      github-token: ${GITHUB_TOKEN}
      keep-history: true
      repo: knewjade/fumen-for-mobile
      local-dir: public/
      target-branch: master
      on:
        branch: master