name: dev-workflow
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile
      - run: yarn test-ci
      - run: yarn webpack-prod
      - run: yarn serve &
      - run: yarn cy-run-ci

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile
      - run: yarn webpack-prod
      - run: sed s/fumen-for-mobile/fumen-for-mobile-dev/ public/manifest.json > public/manifest_copy.json
      - run: mv -f public/manifest_copy.json public/manifest.json
      - run: cat public/manifest.json
      - uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: knewjade/fumen-for-mobile-dev
          publish_branch: master
          enable_jekyll: false
          publish_dir: ./public
