name: prod-workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn test-ci
      - run: yarn webpack-prod
        env:
          DEBUG_ON: false
      - run: yarn serve &
      - run: yarn cy-run-ci

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn webpack-prod
        env:
          DEBUG_ON: false
      - uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: knewjade/fumen-for-mobile
          publish_branch: master
          enable_jekyll: false
          publish_dir: ./dest
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          path: cypress/screenshots/
